### DISCUSSION TITLE
A stable input file for end-users?

### DISCUSSION THREAD

**Discussion by TotoGaz** [GEOS-DEV/GEOS#1911] [Infrastructure]
Hello there!

I've just posted PR https://github.com/GEOSX/GEOSX/pull/1910, which is not for merge but is here as a proof of concept (the code is :see_no_evil:).

- The goal is to propose a stable input file format to our end-users for a subset of GEOSX.
- We can decide what we want to support "_in production_" and what we do not want to (we can even add some `experimental: true` options).
- The goals is not to impose it to our experts who will still benefit from the current situation.

What is done is quite straightforward as explained by the diagram
```mermaid
graph TD
    EU[End user] --> YAML[YAML input]
    YAML -- analyse & transform --> XMLTREE[Parsed XML tree]
    RU[Researcher] --> XML[XML input]
    XML -- parse --> XMLTREE
    XMLTREE --> Simulators
```
The idea is that the end user builds its input file in a way which is somehow unrelated to the GEOSX current `xmls`, _but really related to what he wants to achieve_.
Then a module of GEOSX understands the needs and _builds_ the _appropriate tree representation_. (Basically what this PR poorly does admittedly). 
This "_on-the-fly_" tree representation can _by design be on sync_ with GEOSX because shipped inside of GEOSX :shrug:
_(Who writes and maintains such a module is another discussion.)_

For instance, I’ve been able to hack (there is some hard code) and run the following Laplace simulation.
```
version: 0.1

simulation:
  solvers:
    - type: Laplace
      time_integration_option: steady_state
      field_name: temperature
      linear_solver_parameters:
        - direct_parallel: false
  max_time: 2.
  FEM:
    order: 1

mesh:
  - type: generated
    element_type: [ C3D8 ]
    x_range: [ 0, 1 ]
    y_range: [ 0, 1 ]
    z_range: [ 0, 1 ]
    nx: [ 10 ]
    ny: [ 10 ]
    nz: [ 10 ]
    cell_blocks: [ cb1 ]
  - type: box
    name: source
    point_min: [ -0.01, -0.01, -0.01 ]
    point_max: [ 0.01,  1.01,  1.01 ]
  - type: box
    name: sink
    point_min: [ 0.99, -0.01, -0.01 ]
    point_max: [ 1.01,  1.01,  1.01 ]

regions:
  - type: cells
    cell_blocks: [ cb1 ]

sources_and_sinks:
  - field: temperature
    function: Dirichlet
    location: nodes/source
  - field: temperature
    value: 0.
    location: nodes/sink

functions:
  - name: Dirichlet
    type: table
    variables: [ time ]
    coordinates: [ 0.0, 1.0, 2.0 ]
    values: [ 0.0, 3.e2, 4.e3 ]

outputs:
  - type: vtk
    period: 1.
  - type: silo
    period: 1.
    parallel_threads: 32
  - type: restart
    exact_timestep: false
    period: 1.

```

Note that the tedious and unnecessary definitions of (some) `names` and `events` have been handled automatically by GEOSX. And when there is just one name (_e.g._ for `regions` or `FEM`), then it was possible to deduce it (I’m not sure it’s a good idea, but it’s possible).

Also I've tried to provide more colorful sections.
This surely is a wasted attempt, but it may generate ideas.

At some moment, if an existing options is required but not production grade, we can intercept it and tell the user (_e.g._ kill the simulation unless the `--caution-thin-ice` options is entered explicitly 🤣 )

Another example could be the way we do `TimeHistory`.
```
<Tasks>
  <PackCollection
    name="apertureCollection”
    objectPath="ElementRegions/Fracture/faceElementSubRegion”
    fieldName="elementAperture"/>
</Tasks>

<Outputs>
  <TimeHistory
    name="timeHistoryOutput”
    sources="{/Tasks/apertureCollection}”
    filename="aperture_history" />
</Outputs>  

<Events>
  <PeriodicEvent
    name="timeHistoryOutput”
    targetExactTimestep="0”
    target="/Outputs/timeHistoryOutput"/>
</Events>
```
while the meaningful information is
```
collections:
  - region: regions/fracture/faces # user friendly name
    field: element_aperture 
    file_name: aperture_history
    target_exact_timestep: false
```
(I know that there are options that can be added here and there, but they can also be added in the `yaml`).

I personally strongly believe that it’s more valuable to work on this module, in order to define stable inputs and _only after_ provide GUI/IDE over something stable. This looks like the right order to me.

Any comments?
